### ISSUE TITLE
array values got error

### ISSUE THREAD

**Issue by sciracioglu** [laracasts/Vue-Forms#17]
when form posted return error. because form has array object.

how can i change this function ?

`reset() {
        for (let field in this.originalData) {
            this[field] = '';
        }

        this.errors.clear
![image](https://user-images.githubusercontent.com/2749747/34355468-8bea5e70-ea46-11e7-9b97-957761e4e6d7.png)
();
    }`

**Comment by AndrewMast** [comment]
Use this as your reset function: (note that when creating the Form instance, make sure you pass an array as the original data)

```
reset() {
    for (let field in this.originalData) {
        this[field] = this.originalData[field];
    }

    this.errors.clear();
}
```

**Comment by sciracioglu** [comment]
thanks
